<?php

namespace Test\w3ocom\HashNamed;

use w3ocom\HashNamed\HashNamed;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-08-30 at 10:05:59.
 */
class HashNamedTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var HashNamed
     */
    protected $local_cache_dir;
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $local_cache_dir = "Tests/hash_named_cache";
        $rp = realpath($local_cache_dir . DIRECTORY_SEPARATOR);
        if (empty($rp) && !mkdir($local_cache_dir)) {
            throw new Exception("Can't create hash_named_cache directory for local-cache: $local_cache_dir");
        }
        $this->local_cache_dir = realpath($local_cache_dir);
        $this->object = new HashNamed($this->local_cache_dir);
    }

    /**
     * @covers w3ocom\HashNamed\HashNamed::addRepositories
     */
    public function testAddRepositories() {
        $this->assertEquals(1, $this->object->AddRepositories(['https://w3o.com/hashnamed/']));
        
        $this->expectException(\Exception::class);
        $this->object->AddRepositories([false]);
    }
    
    /**
     * @covers w3ocom\HashNamed\HashNamed::__construct
     */
    public function testConstruct() {
        $obj = new HashNamed($this->local_cache_dir, ['https://w3o.com/hashnamed/']);
        $this->assertIsObject($obj);
        
        // bad path
        $this->expectException(\Exception::class);
        $obj = new HashNamed('not_fund_dir');
    }

    /**
     * @covers w3ocom\HashNamed\HashNamed::installFunction
     */
    public function testInstallFunction() {
        $code = <<<'CODE'
function test($a) {
    return $a + 1;
}
CODE;
        $this->assertEquals('fn_77873608c79f20ee77a94193b2ba9303a3621592', $this->object->installFunction($code));
        
        //$this->expectError();
        //$fn_name = $this->object->installFunction(' ("bad function parameter") ');
        
        $this->expectException(\Exception::class);
        $this->object->installFunction("Bad functoin code {}");
    }

    /**
     * @covers w3ocom\HashNamed\HashNamed::loadHashNamedCode
     */
    public function testLoadHashNamedCode() {
        // loading with good prefix
        $good_prefix = '<' . '?php function fn_77873608c79f20ee77a94193b2ba9303a3621592';
        $file_name = $this->object->LoadHashNamedCode('77873608c79f20ee77a94193b2ba9303a3621592', $good_prefix);
        $this->assertIsString($file_name);
        $this->assertTrue(file_exists($file_name));
        
        // loading with bad prefix
        $file_name = $this->object->LoadHashNamedCode('77873608c79f20ee77a94193b2ba9303a3621592', '');
        $this->assertIsString($file_name);
        $this->assertTrue(file_exists($file_name));
        
        // try to load undefined hash
        $result = $this->object->LoadHashNamedCode('a446bf034aa85ff330a58bb97250bc1072269bff', '');
        $this->assertNull($result);
        
        // try to load bad-length hash
        $this->expectException(\Exception::class);
        $result = $this->object->LoadHashNamedCode('a446bf034aa85ff330a58bb97250bc1072269bf', '');
    }

    /**
     * @covers w3ocom\HashNamed\HashNamed::loadFunction
     */
    public function testLoadFunction() {
        // Successful loading:
        $this->assertNull($this->object->loadFunction('fn_77873608c79f20ee77a94193b2ba9303a3621592'));
        
        // Try undefined function
        $result = $this->object->loadFunction('fn_a446bf034aa85ff330a58bb97250bc1072269bff');
        $this->assertTrue(is_string($result));
        
        // Try illegal functoin name
        $result = $this->object->loadFunction('fn_a446bf034aa85ff330a58bb97250bc1072269bf');
        $this->assertTrue(is_string($result));
    }

    /**
     * @covers w3ocom\HashNamed\HashNamed::__callStatic
     */
    public function test__callStatic() {
        // success
        $x = HashNamed::fn_77873608c79f20ee77a94193b2ba9303a3621592(123);
        $this->assertEquals(124, $x);
        
        // install new function
        $fn_name = HashNamed::installFunction("(\$a) { return \$a * 2; }");
        $this->assertEquals('fn_3449e41850a2be0405f80929668c04a44ef3d2f7', $fn_name);
        
        // undefined
        $this->expectException(\Exception::class);
        $x = HashNamed::fn_77873608c79f20ee77a94193b2ba9303a3621593(123);
    }

    /**
     * @covers w3ocom\HashNamed\HashNamed::__call
     * @todo   Implement test__call().
     */
    public function test__call() {
        $x = $this->object->fn_77873608c79f20ee77a94193b2ba9303a3621592(123);
        $this->assertEquals(124, $x);
    }

}
